### ISSUE TITLE
DataChanged event does not emit comprehensive topics (Developer Quality of Life Improvement)

### ISSUE THREAD

**Issue by trmid** [punk-domains/punk-contracts#6]
### The issue:

When a **[DataChanged event](https://github.com/punk-domains/punk-contracts/blob/701512634e62e80e0c40db3d088097e94822e750/contracts/interfaces/IBasePunkTLD.sol#L18)** is emitted, neither the name nor the new data is included as a topic.

### Why this is an issue:

This makes it slightly more difficult for 3rd party scripts to track data updates. As an example, I have written a script that tracks the latest changes to keep an updated list of only the most recent data per domain. The current logic is roughly as follows:

1. Query the latest **DataChanged** events with RPC
2. Get original TX data for each event from RPC ***<-- this step is the issue***
3. Parse name & data from TX arguments
4. Filter events based on most recent change per name

### Possible Solution:

I propose that the string of the domain changed should be included as an indexed topic like so:

```solidity
event DataChanged(address indexed user, string indexed domain);
```

This would enable quick queries on the history of a name's data changes, and would speed up the example above by allowing duplicate name changes to be filtered before fetching the most recent data. Since names are a string typically under 64 bytes, this would increase event emission gas cost by `(375 gwei/topic * 1 topic) + (64 bytes * 8 gwei/byte) = 887` at most. *(based off the values listed [here](https://github.com/ethereum/go-ethereum/blob/03585ed7a932a6002569c382ab1d3b8d62819b07/params/protocol_params.go#L36))*

Optionally, the data could be included as a non-indexed topic as well, however the gas implications of this are far less clear given the unknown size of the data:

```solidity
event DataChanged(address indexed user, string indexed domain, string newData);
```

**Comment by tempe-techie** [comment]
Hey, good catch, will add it 👍 

Btw, not sure why I didn't get any notification about this issue being posted... 🤔 I need to check my settings.
